import 'package:delimeals/models/category.dart';
import 'package:flutter/material.dart';
import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'German',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg',
    duration: 20,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Toast Hawaii',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQT4TKJiIpOv7w3YAfmxkCmRyyU0kGL90OLPA&usqp=CAU',
    duration: 10,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c3',
    ],
    title: 'Classic hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl: 'https://embed.widencdn.net/img/beef/1akcqwmdqs/exact/classic-beef-cheeseburgers-horizontal.tif?keep=c&u=7fueml',
    duration: 45,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wiener Schnitzel',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl: 'https://lh3.googleusercontent.com/proxy/ljUPsW6uG4TmjXX47bKP9cmcHwo1JvCIcMialD2zStCHH47u3ue2tudgjVtdrjdfXEnh3jK-mxX4XFDRfhqVjFaf8l2vpW0uBlT1Qx-_SnfiajhjOwNIHCtGZnRK6lxRTDACQ5ehSbtSdU7f4sbsqFr5vHm_kQaK-C0U6ad28BKoAsf-8SO4RB1BJcyHA__w9X7y_8kC0CR7apF_zVsf4QRZCVOEuUuJ1WhA9aEHHSYaNvJsMHNI0h_cwLusQeIhQ1yXEg',
    duration: 60,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl: 'https://keyassets-p2.timeincuk.net/wp/prod/wp-content/uploads/sites/53/2007/09/Smoked-salmon-salad-with-Dijon-honey-dressing.jpg',
    duration: 15,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Delicios Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'https://www.oldenburger-professional.com/fileadmin/recipes/Fluffy_date_mousse_with_orange_salad.jpg',
    duration: 240,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://fthmb.tqn.com/Ms2JZRrhlgPRQgxB_Bc904rO-CM=/kids-can-cook-pancakes-recipe-3542699-step-09-77da13f8920d4cb7b9b57af47aa639ab.jpg',
    duration: 20,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indain Chicken Curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl: 'https://salu-salo.com/wp-content/uploads/2017/08/Creamy-Mild-Chicken-Curry-2.jpg',
    duration: 35,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'https://chowhound1.cbsistatic.com/assets/models/promotions/photos/28022/original/10854_chocolate_souffle.jpg',
    duration: 45,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparagus Salad With Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl: 'https://www.backyardfarms.com/assets/img/uploads/recipes/pasta_salad_with_tomatoes%2C_spinach%2C_and_avo.png',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatos',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash, peel and cut the asparugus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
];
